version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: level2
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    volumes:
      - pgdata:/var/lib/pgsql/data
    ports:
      - "5432:5432"


  level2:
    build: .
    depends_on:
      - postgres
    environment:
      DATABSE_URL: postgres://guest:guest@127.0.0.1:5432/level2
      PORT: "8080"
    ports:
      - "8080:8080"

volumes:
  pgdata:
