version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: level2
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    volumes:
      - pgdata:/var/lib/pgsql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    volumes:
      - ./deps/nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/certs:/etc/nginx/certs:ro
    ports:
      - "443:443"

  level2:
    build: .
    depends_on:
      - postgres
    environment:
      PORT: "8080"
      DATABASE_URL: postgres://guest:guest@postgres:5432/level2
      METADATA_API: http://internal-api-gateway.service.prod.consul/graphql
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge

volumes:
  pgdata:
