version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: level2
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    volumes:
      - pgdata:/var/lib/pgsql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
