name:               nso-level2
version:            0.2.0
synopsis:           NSO Level 2 Data Processing
homepage:           https://github.com/DKISTDC/Level2
license:            BSD-3-Clause
author:             Sean Hess
maintainer:         shess@nso.edu
category:           System, Science


extra-doc-files:
  - README.md
  - DEVELOPMENT.md

extra-source-files:
  - deps/metadata.graphql

language: GHC2021


ghc-options:
  - -Wall

default-extensions:
  - TypeFamilies
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - DuplicateRecordFields
  - LambdaCase
  - NoImplicitPrelude
  - NoFieldSelectors

dependencies:
  - base >=4.16.4.0
  # - aeson == 2.1.2.1
  # - bytestring
  # - effectful == 2.3.0.0
  - text
  # - amqp-worker >= 2.0
  # - data-diverse >= 4.7
  # - tagged
  # - lens
  # - hasql
  # - time
  # - exceptions
  # - string-interpolate
  # - morpheus-graphql-client == 0.27.3
  # - morpheus-graphql-core == 0.27.3
  # - morpheus-graphql == 0.27.3
  # - modern-uri
  # - req
  # - containers
  # - string-conversions
  # - rel8 == 1.4.1.0
  # - web-view >= 0.2.3
  # - hyperbole == 0.1.1
  # - warp == 3.3.31
  # - wai-extra


executables:
  fake:
    source-dirs: fake
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

# executables:
#   level2:
#     source-dirs: app
#     main: Main.hs
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N


# tests:
#   tests:
#     main:        Spec.hs
#     source-dirs: test/
#     build-tools: sydtest-discover
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#       - web-view
#       - sydtest >= 0.15

