name:               nso-level2
version:            0.3.1
synopsis:           NSO Level 2 Data Processing
homepage:           https://github.com/DKISTDC/Level2
license:            BSD-3-Clause
author:             Sean Hess
maintainer:         shess@nso.edu
category:           System, Science


extra-doc-files:
  - README.md
  - DEVELOPMENT.md

extra-source-files:
  - deps/metadata.graphql

language: GHC2021


ghc-options:
  - -Wall
  - -fdefer-typed-holes

default-extensions:
  - TypeFamilies
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - DuplicateRecordFields
  - NoImplicitPrelude
  - NoFieldSelectors
  - LambdaCase

dependencies:
  - base >= 4.18
  - nso-level2-types

  - aeson
  - amqp-worker >= 2.0.1
  - atomic-css >= 0.1.0
  - binary
  - bytestring
  - casing
  - containers
  - data-default
  - data-diverse >= 4.7
  - directory
  - effectful >= 2.3 && <3
  - exceptions
  - filepath
  - globus >= 0.2.1
  - hasql
  - http-api-data
  - http-client
  - http-client-tls
  - http-types
  - hyperbole == 0.6.0
  - lens
  - massiv
  - megaparsec
  - monad-loops
  - network-uri
  - random
  - rel8 >= 1.6
  - string-conversions
  - string-interpolate
  - tagged
  - telescope >= 0.4
  - text
  - time
  - unix
  - unordered-containers
  - uuid
  - wai
  - wai-extra
  - wai-middleware-static
  - warp >= 3.4


library:
  source-dirs: src


executables:
  level2:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - nso-level2



tests:
  spec:
    main: Spec.hs
    source-dirs: test/
    build-tools: skeletest:skeletest-preprocessor
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -F -pgmF=skeletest-preprocessor
    dependencies:
      - nso-level2
      - atomic-css
      - Diff >= 0.5 && <1.0
      - skeletest

