name:               nso-level2
version:            0.3.0
synopsis:           NSO Level 2 Data Processing
homepage:           https://github.com/DKISTDC/Level2
license:            BSD-3-Clause
author:             Sean Hess
maintainer:         shess@nso.edu
category:           System, Science


extra-doc-files:
  - README.md
  - DEVELOPMENT.md

extra-source-files:
  - deps/metadata.graphql

language: GHC2021


ghc-options:
  - -Wall

default-extensions:
  - TypeFamilies
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - DuplicateRecordFields
  - LambdaCase
  - NoImplicitPrelude
  - NoFieldSelectors
  - StrictData

dependencies:
  - base >=4.16.4.0
  - nso-level2-types
  - web-view >= 0.2.3
  - warp == 3.3.31
  - wai-extra
  - http-types
  - time
  - text
  - tagged
  - filepath
  - string-interpolate
  - string-conversions
  - req
  - rel8 == 1.4.1.0
  - random
  # - morpheus-graphql-core == 0.27.3
  # - morpheus-graphql-client == 0.27.3
  # - morpheus-graphql == 0.27.3
  - modern-uri
  - lens
  - hyperbole == 0.3.3
  - hasql
  - exceptions
  - effectful == 2.3.0.0
  - data-diverse >= 4.7
  - data-diverse
  - containers
  - bytestring
  - aeson == 2.1.2.1
  - http-api-data
  - globus
  # - amqp-worker >= 2.0


library:
  source-dirs: src


executables:
  level2:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - nso-level2


tests:
  tests:
    main:        Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - nso-level2
      - web-view
      - sydtest >= 0.15

