name:               nso-level2
version:            0.3.1
synopsis:           NSO Level 2 Data Processing
homepage:           https://github.com/DKISTDC/Level2
license:            BSD-3-Clause
author:             Sean Hess
maintainer:         shess@nso.edu
category:           System, Science


extra-doc-files:
  - README.md
  - DEVELOPMENT.md

extra-source-files:
  - deps/metadata.graphql

language: GHC2021


ghc-options:
  - -Wall
  - -fdefer-typed-holes

default-extensions:
  - TypeFamilies
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - DuplicateRecordFields
  - LambdaCase
  - NoImplicitPrelude
  - NoFieldSelectors
  - StrictData

dependencies:
  - base >=4.16.4.0
  - nso-level2-types
  - web-view >= 0.5.0
  - warp == 3.3.31
  - wai-extra
  - http-types
  - casing
  - time
  - text
  - tagged
  - filepath
  - string-interpolate
  - string-conversions
  - req
  - rel8 >= 1.5.0
  - random
  - modern-uri
  - lens
  - hyperbole == 0.4.1
  - hasql
  - exceptions
  - binary
  - effectful >= 2.3 && <3
  - data-diverse >= 4.7
  - data-diverse
  - containers
  - unordered-containers
  - bytestring
  - aeson
  - http-api-data
  - globus >= 0.1.3
  - massiv
  - telescope >= 0.2 && < 0.3
  - uuid
  - megaparsec
  - monad-loops


library:
  source-dirs: src


executables:
  level2:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - nso-level2



tests:
  spec:
    main: Spec.hs
    source-dirs: test/
    build-tools: skeletest:skeletest-preprocessor
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -F -pgmF=skeletest-preprocessor
    dependencies:
      - nso-level2
      - web-view
      - Diff >= 0.5 && <1.0
      - skeletest

