name:               nso-level2-types
version:            0.3.1
synopsis:           Types for NSO Level2 System
homepage:           https://github.com/DKISTDC/Level2
license:            BSD-3-Clause
author:             Sean Hess
maintainer:         shess@nso.edu
category:           System, Science


extra-doc-files:
  - README.md

language: GHC2024

ghc-options:
  - -Wall

default-extensions:
  - TypeFamilies
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - DuplicateRecordFields
  - NoImplicitPrelude
  - NoFieldSelectors
  - StrictData

dependencies:
  - base >=4.19 && <5
  - time
  - text
  - tagged
  - string-interpolate
  - string-conversions
  - filepath
  - rel8
  - hasql
  - random
  - modern-uri
  - lens
  - hyperbole >= 0.4.3
  - exceptions
  - effectful >= 2.4 && <3
  - http-api-data
  - http-client
  - http-types
  - data-diverse
  - data-diverse
  - containers
  - bytestring
  - aeson
  - globus >= 0.1.3
  - telescope >= 0.2 && <0.3
  - scientific


library:
  source-dirs: src


