name:               nso-level2-types
version:            0.3.1
synopsis:           Types for NSO Level2 System
homepage:           https://github.com/DKISTDC/Level2
license:            BSD-3-Clause
author:             Sean Hess
maintainer:         shess@nso.edu
category:           System, Science


extra-doc-files:
  - README.md

language: GHC2021

ghc-options:
  - -Wall

default-extensions:
  - TypeFamilies
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - DuplicateRecordFields
  - NoImplicitPrelude
  - NoFieldSelectors
  - LambdaCase

dependencies:
  - base >=4.18 && <5
  - aeson
  - ansi-terminal
  - bytestring
  - casing
  - containers
  - data-diverse
  - data-diverse
  - effectful >= 2.4 && <3
  - exceptions
  - filepath
  - globus >= 0.2.1
  - hasql
  - http-api-data
  - http-client
  - http-types
  - hyperbole == 0.6.0
  - lens
  - megaparsec
  - modern-uri
  - network-uri
  - random
  - rel8
  - scientific
  - string-conversions
  - string-interpolate
  - tagged
  - telescope >= 0.4
  - text
  - time


library:
  source-dirs: src


