-- DDL generated by Postico 2.3.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE inversions (
    inversion_id text PRIMARY KEY,
    program_id text NOT NULL,
    proposal_id text NOT NULL,
    created timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    error text,
    dataset_ids text[],
    inversion_software text,
    generate_transfer timestamp without time zone,
    generate_fits timestamp without time zone,
    generate_asdf timestamp without time zone,
    publish timestamp without time zone,
    notes text NOT NULL DEFAULT ''::text,
    deleted timestamp without time zone
);

-- Indices -------------------------------------------------------

CREATE INDEX idx_inversions_program ON inversions(program_id);
CREATE INDEX idx_inversions_proposal ON inversions(proposal_id);
CREATE INDEX idx_inversions_datasets ON inversions(dataset_ids);
