module NSO.Image.Primary where

import Control.Exception (Exception)
import Data.Massiv.Array ()
import Effectful
import Effectful.Error.Static
import Effectful.GenRandom
import NSO.Image.Headers
import NSO.Image.Headers.Parse (ParseError, runParseError)
import NSO.Prelude
import NSO.Types.Common
import NSO.Types.Inversion (Inversion)
import Telescope.Fits as Fits


data PrimaryHeader = PrimaryHeader
  { observation :: Observation
  , telescope :: Telescope
  , datacenter :: Datacenter
  , dkist :: DKISTHeader
  , adaptive :: AdaptiveOptics
  , contributing :: ContribExpProp
  }
  deriving (Generic)


instance ToHeader PrimaryHeader where
  toHeader h = writeHeader $ do
    sectionHeader "Observation" "Keys describing the observation and general metadata"
    addKeywords h.observation

    sectionHeader "Telescope" "Keys describing the pointing and op of the Telescope"
    addKeywords h.telescope

    sectionHeader "Datacenter" "Keys generated by the DKIST data center to describe processing performed, archiving or extra metadata"
    addKeywords h.datacenter
    addKeywords h.contributing

    sectionHeader "DKIST Operations" "Information about this configuration or operations of the facility when generating this data"
    addKeywords h.dkist

    sectionHeader "Adaptive Optics" "Keys describing aspects of the adaptive optics system"
    addKeywords h.adaptive


primaryHeader :: (Error PrimaryError :> es, GenRandom :> es) => Id Inversion -> Header -> Eff es PrimaryHeader
primaryHeader ii l1 = runParseError PrimaryParse $ do
  observation <- observationHeader l1
  telescope <- telescopeHeader l1
  datacenter <- datacenterHeader l1 ii
  dkist <- dkistHeader l1
  contributing <- contribExpProp l1
  adaptive <- adaptiveOpticsHeader l1
  pure $ PrimaryHeader{observation, telescope, datacenter, dkist, adaptive, contributing}


primaryHDU :: PrimaryHeader -> PrimaryHDU
primaryHDU h = PrimaryHDU (toHeader h) emptyDataArray


data PrimaryError
  = PrimaryParse ParseError
  deriving (Show, Exception, Eq)
