name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      IMAGE: level2

    # https://docs.github.com/en/actions/learn-github-actions/contexts
    steps:
    - uses: actions/checkout@v3

    - name: Add Variables
      run: |
        SHA_SHORT=$(git rev-parse --short HEAD)
        echo "SHA_SHORT=$SHA_SHORT" >> $GITHUB_ENV

    - name: Check Variables
      run: |
        echo "SHA_SHORT=$SHA_SHORT"

    # https://github.com/docker/build-push-action?tab=readme-ov-file
    # https://stackoverflow.com/questions/63805317/publish-docker-image-to-jfrog-artifactory-from-github-actions-cicd-pipeline
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Artifactory
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.ARTIFACTORY }}
        username: ${{ secrets.ARTIFACTORY_USER }}
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        # push: true
        tags: ${{vars.ARTIFACTORY}}/${{env.IMAGE}}:${{vars.VERSION_PREFIX}}.${{github.ref_name}}.${{env.SHA_SHORT}}
        cache-from: type=gha
        cache-to: type=gha,mode=max
