name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "${{env.ARTIFACTORY_URL}}/level2:${{env.VERSION_PREFIX}}.${{env.branch}}.${GITHUB_SHA::6}"
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: |
        echo "CHECK $VERSION_PREFIX"
        echo "IMAGE_NAME=$IMAGE_NAME"
        echo "ARTIFACTORY_USER=$ARTIFACTORY_USER"
    - name: Docker login
      run: docker login dkistdc-docker.jfrog.io --username $ARTIFACTORY_USER --password $ARTIFACTORY_PASSWORD
    - name: Docker Build
      run: docker build . --tag $IMAGE_NAME
    - name: Docker Push
      run: docker push -a $IMAGE_NAME
