name: Haskell CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        haskell: [ 9.4.7 ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Check Haskell version
      run: |
        ghcup --version
        ghc --version
    - name: Install Haskell ${{ matrix.haskell }}
      run: |
        ghcup install ghc ${{ matrix.haskell }}
        ghcup set ghc ${{ matrix.haskell }}
    - name: Check Haskell version
      run: ghc --version

    - name: Cache
      uses: actions/cache@v3
      env:
        # increment this when you want to rebuild the cache
        cache-name: cache-cabal-v5
      with:
        path: /home/runner/.local/state/cabal
        # key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    # - name: Test
    #   run: |
    #     cabal update
    #     ls $HOME/.config/cabal
    #     cat $HOME/.config/cabal/config
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal run
    - name: Check Cache
      # run: find $HOME -type d -name "9.4.7"
      run: |
        pwd
        find $HOME -type d -name "*9.4.7*"

